### ISSUE TITLE
docs: combine nuxt-composition-api and nuxt-typed-vue

### ISSUE THREAD

**Issue by regenrek** [danielroe/typed-vuex#113]
**📚 Is your documentation request related to a problem? Please describe.**

Hi does nuxt-typed-vuex and nuxt-composition-api work together out of the box.
Do you have any example repo where these two are used together?

Thanks in advance!

**Comment by danielroe** [comment]
Yes, good idea. I'll add some composables to this package. Any preferences on the way you would like to use it?

**Comment by regenrek** [comment]
Hi,

yeah, it would be interesting how you would use (memory) state management in combination with for example [graphql](https://hasura.io/) to read/write data. For example using `nuxt-typed-vuex` to manage `todos` state and use `nuxt-composition-api` composables for crud operations. 

Kind of this [here](https://github.com/zebbra/e-session/tree/master/frontend/store) (rooms - state) and [here](https://github.com/zebbra/e-session/blob/master/frontend/composable/useRoom.ts) (rooms - graphql)

**Comment by nimarion** [comment]
Any updates?

**Comment by danielroe** [comment]
With the next release of `@nuxtjs/composition-api` this will be as simple as creating your own `useAccessor` function.
```js
import { wrapProperty } from '@nuxtjs/composition-api'
export const useAccessor = wrapProperty('$accessor', false)

// You can now get a fully typed accessor within `setup()`

export default defineComponent({
  setup() {
    const accessor = useAccessor()
    // You can now access a fully typed store accessor in your component
  },
})
```

**Comment by P4sca1** [comment]
@danielroe In how far is this different from `const { $accessor } = useContext()`?
Also I noticed that the state is not reactive in a way. You have to manually wrap each attribute that you want to use in a computed property, e.g.:
```ts
const { $accessor } = useContext()
    const authenticatedUser = computed(() => $accessor.authenticatedUser )
    
    return {
      authenticatedUser
    }
```
Without the computed, resetting `authenticatedUser` to another value wont update the component.
Is this a limitation of Vue 2 and can this process somehow be simplified, because wrapping everything with a computed is quite verbose.
